### ISSUE TITLE
Very slow for a matrix of azimuths

### ISSUE THREAD

**Issue by edwardbair** [DozierJeff/Topographic-Horizons#1]
For a matrix of varying azimuths, this code will take a very long time. Variations < 1 deg and NaNs can be ignored.
Thus I suggest using code from the deprecated GetHorizon.m here.

azm = round(azm); % just need to the nearest degree
u = unique(azm(~isnan(azm)));

https://github.com/DozierJeff/Topographic-Horizons/blob/bcab07cf9cb97ff0df68a73a0d8aac654bcda539/StorageFunctions/h5getHorizon.m#L51

**Comment by DozierJeff** [comment]
Deprecated. Use writeHorizon. Just run over N horizon angles, typically 64 enough. Then writeHorizon to a .mat file saves the interpolation function.

From: Ned Bair ***@***.***>
Sent: Monday, June 27, 2022 19:24
To: DozierJeff/Topographic-Horizons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DozierJeff/Topographic-Horizons] Very slow for a matrix of azimuths (Issue #1)


For a matrix of varying azimuths, this code will take a very long time. Variations < 1 deg and NaNs can be ignored.
Thus I suggest using code from the deprecated GetHorizon.m here.

azm = round(azm); % just need to the nearest degree
u = unique(azm(~isnan(azm)));

https://github.com/DozierJeff/Topographic-Horizons/blob/bcab07cf9cb97ff0df68a73a0d8aac654bcda539/StorageFunctions/h5getHorizon.m#L51

**Comment by edwardbair** [comment]
Why is the deprecated function still available, without any documentation that it shouldn't be used?

**Comment by DozierJeff** [comment]
It still works for hdf 5 files. I tend to use .mat files that provide interpolation between measured values.

Jeff ***@***.***
Sent from my phone
________________________________
