### ISSUE TITLE
error

### ISSUE THREAD

**Issue by edwardbair** [DozierJeff/Topographic-Horizons#2]
Using 'nHorz' 360 or 356 causes the following error

Error using smooth3 (line 65)
All elements of SIZE must be odd integers greater than or equal to 1.

https://github.com/DozierJeff/Topographic-Horizons/blob/a9cd5bfd7d36f3f7c8628ea0e12ee59ceccd70b9/horizonAllDirections.m#L286

**Comment by DozierJeff** [comment]
fixed
